import importlib.util
import os
import json5
from lxml import etree
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from email.utils import format_datetime, parsedate_to_datetime
from urllib.parse import urljoin, urlparse

def load_and_run_script(script_name, url=None, app_ids=None):
    script_path = os.path.join(os.path.dirname(__file__), 'patterns', script_name)
    spec = importlib.util.spec_from_file_location("module.name", script_path)
    if spec.loader is None:
        raise FileNotFoundError(f"Script {script_name} could not be loaded. Check if the file exists.")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    
    if app_ids:
        data = module.fetch_data_with_id(app_ids)
    else:
        data = module.fetch_data(url)
        
    return data

def clean_xml(xml_str):
    xml_str = re.sub(r'<!--.*?-->', '', xml_str, flags=re.DOTALL)
    parser = etree.XMLParser(remove_blank_text=True)
    root = etree.fromstring(xml_str, parser)
    for element in root.xpath(".//script"):
        element.getparent().remove(element)
    for element in root.xpath(".//spoiler"):
        element.getparent().remove(element)
    return etree.tostring(root, pretty_print=True, encoding='UTF-8')


def infer_channel_link(explicit_link, feed_items):
    if explicit_link:
        return explicit_link

    for item in feed_items:
        link = (item.get('link') or '').strip()
        if link.startswith('http://') or link.startswith('https://'):
            parsed = urlparse(link)
            if parsed.scheme and parsed.netloc:
                return f"{parsed.scheme}://{parsed.netloc}/"
    return ""


def normalize_pub_date(value):
    if not value:
        return ""

    try:
        dt = parsedate_to_datetime(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return format_datetime(dt.astimezone(timezone.utc))
    except Exception:
        pass

    try:
        dt = datetime.fromisoformat(value.replace('Z', '+00:00'))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return format_datetime(dt.astimezone(timezone.utc))
    except Exception:
        return ""


def pub_date_sort_key(item):
    raw_pub_date = item.get('pubDate')
    normalized = normalize_pub_date(raw_pub_date)
    if not normalized:
        return datetime.min.replace(tzinfo=timezone.utc)

    try:
        return parsedate_to_datetime(normalized)
    except Exception:
        return datetime.min.replace(tzinfo=timezone.utc)


def generate_xml(feed_items, file_name, channel_title=None, channel_link=None, channel_description=None):
    feed_items = sorted(feed_items, key=pub_date_sort_key, reverse=True)

    safe_channel_title = channel_title or os.path.splitext(os.path.basename(file_name))[0]
    safe_channel_title = safe_channel_title.replace('_', ' ').strip() or "Multi-RSS Feed"
    safe_channel_link = infer_channel_link(channel_link, feed_items)
    safe_channel_description = channel_description or f"RSS feed for {safe_channel_title} generated by Multi-RSS."

    root = etree.Element('rss', version="2.0", nsmap={
        'atom': "http://www.w3.org/2005/Atom",
        'content': "http://purl.org/rss/1.0/modules/content/"
    })
    channel = etree.SubElement(root, 'channel')

    channel_title_element = etree.SubElement(channel, 'title')
    channel_title_element.text = safe_channel_title

    channel_link_element = etree.SubElement(channel, 'link')
    channel_link_element.text = safe_channel_link or "https://github.com/ALeX400/Multi-RSS"

    channel_description_element = etree.SubElement(channel, 'description')
    channel_description_element.text = safe_channel_description

    language_element = etree.SubElement(channel, 'language')
    language_element.text = "en-US"

    generator_element = etree.SubElement(channel, 'generator')
    generator_element.text = "Multi-RSS"

    last_build_date_element = etree.SubElement(channel, 'lastBuildDate')
    last_build_date_element.text = format_datetime(datetime.now(timezone.utc))

    for item in feed_items:
        item_element = etree.SubElement(channel, 'item')
        title = etree.SubElement(item_element, 'title')
        title.text = item.get('title', 'No title')

        link = etree.SubElement(item_element, 'link')
        link.text = item.get('link', '#')

        guid_value = item.get('guid') or item.get('link') or item.get('title', 'No title')
        guid = etree.SubElement(item_element, 'guid')
        guid.text = guid_value
        if not (guid_value.startswith('http://') or guid_value.startswith('https://')):
            guid.set('isPermaLink', 'false')

        description = etree.SubElement(item_element, 'description')
        description.text = etree.CDATA(item.get('description', 'No description'))

        content_encoded = etree.SubElement(item_element, '{http://purl.org/rss/1.0/modules/content/}encoded')
        content_encoded.text = etree.CDATA(item.get('description', 'No description'))
        
        # Add optional pubDate if it exists
        pub_date = normalize_pub_date(item.get('pubDate'))
        if pub_date:
            pub_date_element = etree.SubElement(item_element, 'pubDate')
            pub_date_element.text = pub_date

    xml_bytes = etree.tostring(root, pretty_print=True, encoding='UTF-8')
    with open(file_name, 'wb') as file:
        file.write(xml_bytes)

def print_progress_bar(iteration, total, length=50):
    if total <= 0:
        return
    percent = 100 * (iteration / float(total))
    print(f"Progress: {iteration}/{total} ({percent:.1f}%) complete")

def process_site(site_name, site_info):
    print(f"Processing site: '{site_name}'")
    try:
        steam = site_info.get('Steam', False)
        app_ids = site_info.get('AppIDs') if steam else None
        base_url = site_info.get('url') if not steam else None
        categories = site_info.get('category', [])
        script = site_info['script']
        file_name = site_info.get('FileName') or site_name
        if not file_name.lower().endswith('.xml'):
            file_name += '.xml'
        file_name = os.path.join('rss', file_name)
        all_articles_data = []
        
        if categories:
            site_dir = os.path.join('rss', site_name)
            if not os.path.exists(site_dir):
                os.makedirs(site_dir)
            total_categories = len(categories)
            current_category = 0
            with ThreadPoolExecutor() as executor:
                futures = {
                    executor.submit(
                        load_and_run_script,
                        script,
                        urljoin(base_url.rstrip('/') + '/', category.lstrip('/'))
                    ): category
                    for category in categories
                }
                for future in as_completed(futures):
                    category = futures[future]
                    try:
                        articles_data = future.result()
                        if articles_data:
                            category_dir = os.path.join(site_dir, category)
                            if not os.path.exists(category_dir):
                                os.makedirs(category_dir)
                            category_file_name = os.path.join(category_dir, f"{category}.xml")
                            category_url = urljoin(base_url.rstrip('/') + '/', category.lstrip('/'))
                            generate_xml(
                                articles_data,
                                category_file_name,
                                channel_title=f"{site_name} - {category}",
                                channel_link=category_url,
                                channel_description=f"RSS feed for category '{category}' from {site_name}."
                            )
                            all_articles_data.extend(articles_data)
                    except Exception as e:
                        print(f"Failed to process category {category} for site {site_name}: {e}")
                    current_category += 1
                    #print_progress_bar(current_category, total_categories)
            #print()  # Finalize category progress bar output
        else:
            if app_ids:
                articles_data = load_and_run_script(script, app_ids=app_ids)
            else:
                articles_data = load_and_run_script(script, base_url)
            
            if articles_data:
                generate_xml(
                    articles_data,
                    file_name,
                    channel_title=site_name,
                    channel_link=base_url,
                    channel_description=f"RSS feed for {site_name}."
                )
                all_articles_data.extend(articles_data)
        
        if all_articles_data:
            return site_name, True
        else:
            print(f"No data found for site '{site_name}'")
            return site_name, False
    except Exception as e:
        print(f"Failed to process site {site_name}: {e}")
        return site_name, False

def replace_dynamic_parameters(url):
    current_year = datetime.now().year
    url = url.replace("{year}", str(current_year))
    return url

def main():
    with open('config.json', 'r', encoding='utf-8') as file:
        config = json5.load(file)
    output_dir = 'rss'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    patterns_dir = os.path.join(os.path.dirname(__file__), 'patterns')
    if not os.path.exists(patterns_dir):
        os.makedirs(patterns_dir)
        raise Exception("Patterns directory created. Please add pattern scripts and retry.")
    groups = config.get('Groups', {})
    sites = config.get('Sites', {})
    total_tasks = len(groups) + len(sites)
    current_task = 0
    if groups:
        for group_index, (group_name, group_info) in enumerate(groups.items()):
            print(f'Processing group {group_index + 1}/{len(groups)}: {group_name}')
            group_feed = []
            with ThreadPoolExecutor() as executor:
                future_to_url = {executor.submit(load_and_run_script, script, url): (url, script) for url, script in zip(group_info['Urls'], group_info['Scripts'])}
                for future in as_completed(future_to_url):
                    url, script = future_to_url[future]
                    try:
                        articles_data = future.result()
                        group_feed.extend(articles_data)
                    except Exception as e:
                        print(f"Failed to process {url} with script {script}: {e}")
                        continue
            file_name = os.path.join(output_dir, group_info.get('FileName') or f'{group_name}.xml')
            generate_xml(
                group_feed,
                file_name,
                channel_title=group_name,
                channel_link=group_info['Urls'][0] if group_info.get('Urls') else None,
                channel_description=f"Aggregated RSS feed for group {group_name}."
            )
            print(f"Finished processing group {group_name}\n")
            current_task += 1
    success_count = 0
    with ThreadPoolExecutor() as executor:
        future_to_site = {executor.submit(process_site, site_name, site_info): (site_name, site_info) for site_name, site_info in sites.items()}
        for future in as_completed(future_to_site):
            site_name, site_info = future_to_site[future]
            try:
                site_name, success = future.result()
                if success:
                    success_count += 1
            except Exception as e:
                print(f"Failed to process site {site_name}: {e}")
            current_task += 1
            print_progress_bar(current_task, total_tasks)
    print(f"\nFinished {success_count}/{len(sites)} successfully.")

if __name__ == "__main__":
    main()
