name: Merge PR

on:
  pull_request:
    types:
      - opened

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge pull request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
