name: Sync working-branch to main

on:
  push:
    branches:
      - working-branch

jobs:
  sync-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout working-branch
        uses: actions/checkout@v3
        with:
          ref: working-branch

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main branch
        run: git checkout main

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Sync working-branch to main
        run: |
          git merge --no-ff working-branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
