name: Update index.md

on:
  push:
    paths:
      - 'rss/*.xml'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Update index.md
        run: |
          python update_index.py

      - name: Delete remote temp-branch if it exists
        run: |
          git push origin --delete temp-branch || true

      - name: Commit and push changes to temporary branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b temp-branch
          git add rss/index.md
          git commit -m "Update index.md with list of XML files"
          git push --set-upstream origin temp-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update index.md with list of XML files"
          base: main
          branch: temp-branch
          title: "Update index.md"
          body: "This PR updates index.md with the latest list of XML files."
