name: RSS Feed Updater

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 lxml tqdm

    - name: Run main RSS update script
      run: python main.py

    - name: Commit and push if there are changes in the RSS directory
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatically updated RSS feeds" && git push)
